//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPMurtazinIS121.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        public Employees()
        {
            this.WorkSchedules = new HashSet<WorkSchedules>();
            this.InventoryAlerts = new HashSet<InventoryAlerts>();
            this.InventoryTransactions = new HashSet<InventoryTransactions>();
            this.Orders = new HashSet<Orders>();
        }
    
        public int EmployeeID { get; set; }
        public string FIO { get; set; }
        public Nullable<int> PositionID { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> HireDate { get; set; }
    
        public virtual PositionsEmployee PositionsEmployee { get; set; }
        public virtual ICollection<WorkSchedules> WorkSchedules { get; set; }
        public virtual ICollection<InventoryAlerts> InventoryAlerts { get; set; }
        public virtual ICollection<InventoryTransactions> InventoryTransactions { get; set; }
        public virtual ICollection<Orders> Orders { get; set; }
    }
}
