//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPMurtazinIS121.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingredients
    {
        public Ingredients()
        {
            this.IngredientSupplier = new HashSet<IngredientSupplier>();
            this.InventoryAlerts = new HashSet<InventoryAlerts>();
            this.Recipes = new HashSet<Recipes>();
        }
    
        public string IngredientsName { get; set; }
        public string TypeIngredients { get; set; }
        public string UnitOfMeasurement { get; set; }
        public Nullable<decimal> KolichSklad { get; set; }
        public Nullable<int> MinimKolich { get; set; }
        public Nullable<int> KolichUpakovka { get; set; }
        public Nullable<int> CostForOne { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public int IngredientID { get; set; }
    
        public virtual TypeIngredients TypeIngredients1 { get; set; }
        public virtual UnitOfMeasurement UnitOfMeasurement1 { get; set; }
        public virtual ICollection<IngredientSupplier> IngredientSupplier { get; set; }
        public virtual ICollection<InventoryAlerts> InventoryAlerts { get; set; }
        public virtual ICollection<Recipes> Recipes { get; set; }
    }
}
