//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPMurtazinIS121.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryAlerts
    {
        public int AlertID { get; set; }
        public System.DateTime AlertDate { get; set; }
        public bool IsResolved { get; set; }
        public Nullable<int> ResolvedBy { get; set; }
        public Nullable<System.DateTime> ResolvedDate { get; set; }
        public Nullable<int> IngredientID { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Ingredients Ingredients { get; set; }
    }
}
