//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPMurtazinIS121.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuItems
    {
        public MenuItems()
        {
            this.OrderDetails = new HashSet<OrderDetails>();
            this.Recipes = new HashSet<Recipes>();
        }
    
        public int MenuItemID { get; set; }
        public int CategoryID { get; set; }
        public string ItemName { get; set; }
        public string Description { get; set; }
        public string ImagePath { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Calories { get; set; }
    
        public virtual MenuCategories MenuCategories { get; set; }
        public virtual ICollection<OrderDetails> OrderDetails { get; set; }
        public virtual ICollection<Recipes> Recipes { get; set; }
    }
}
