//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPMurtazinIS121.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipes
    {
        public int RecipeID { get; set; }
        public int MenuItemID { get; set; }
        public decimal Quantity { get; set; }
        public string Instructions { get; set; }
        public Nullable<int> IngredientID { get; set; }
    
        public virtual Ingredients Ingredients { get; set; }
        public virtual MenuItems MenuItems { get; set; }
    }
}
