//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPMurtazinIS121.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Suppliers
    {
        public Suppliers()
        {
            this.IngredientSupplier = new HashSet<IngredientSupplier>();
        }
    
        public string Name { get; set; }
        public string Type { get; set; }
        public string YuridAdres { get; set; }
        public Nullable<double> INN { get; set; }
        public string FIO { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Logo { get; set; }
        public Nullable<decimal> RatingReliability { get; set; }
        public int IDSuppliers { get; set; }
    
        public virtual ICollection<IngredientSupplier> IngredientSupplier { get; set; }
        public virtual TypeSupplier TypeSupplier { get; set; }
    }
}
