//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPMurtazinIS121.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeSupplier
    {
        public TypeSupplier()
        {
            this.Suppliers = new HashSet<Suppliers>();
        }
    
        public string Type { get; set; }
    
        public virtual ICollection<Suppliers> Suppliers { get; set; }
    }
}
